### ISSUE TITLE
Project does not compile for Win64 target

### ISSUE THREAD

**Issue by joachimmarder** [mendrix/DelphiCodeCoverage#2]
When choosing Win64 as target platform, there is a compiler error:

```
[dcc64 Error] Debugger.pas(906): E2003 Undeclared identifier: 'Rip'
[dcc64 Fatal Error] CodeCoverage.dpr(21): F2063 Could not compile used unit 'Debugger.pas'

```

Are you able to compile locally on yur machine?

**Comment by joachimmarder** [comment]
> The _CONTEXT record is not yet Win64 compatible (and so the Rip-register is unknown), but we can't simply switch to Winapi.Windows, because of some other functionality in the debugger.

Can you elaborate more on this? The definition in WinApi.Windows looks good otherwise and is e.g. used by MadExcept. But I have to admit that this stuff is not my area of expertise.

**Comment by mendrix** [comment]
I have modified `JwaWinNT.pas` and some minor changes in `Debugger.pas` to solve this. Also WOW64 debugging support is now added.

**Comment by joachimmarder** [comment]
Thank you, it now compiles successfully in Delphi 10.4.2 with one (non-relevant) warning:

`[dcc64 Warning] Debugger.pas(1038): W1036 Variable 'MachineType' might not have been initialized`
