### ISSUE TITLE
CodeCoverage.exe should pass on an exit code <> 0

### ISSUE THREAD

**Issue by joachimmarder** [mendrix/DelphiCodeCoverage#3]
If the monitored executable exits with an exit code <> 0, CodeCoverage.exe should use this exit code instead of exiting with 0.

**Comment by Laurensvanrun** [comment]
You should pass the commandline parameter `-tec` to do this.

**Comment by joachimmarder** [comment]
OK, thanks. This command line parameter is missing in the Readme.md.
